### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Luongzz** [secchanu/discord-custom-game-bot#1]
![image](https://github.com/secchanu/discord-custom-game-bot/assets/37655807/10e31625-2371-4bed-a459-6772dd4c08ff)

**Comment by secchanu** [comment]
Hi! Thank you for your message!
What language setting are you using in Discord?

**Comment by Luongzz** [comment]
> Hi! Thank you for your message! What language setting are you using in Discord?

I switched to Vietnamese and English

**Comment by Luongzz** [comment]
can you show me how to add map data, because i get this error due to missing map data

**Comment by secchanu** [comment]
Check which branch you are using.
If you are using it for VALORANT, you must use the valorant branch, not the main branch.
Or, even easier, you can add a BOT that I host, and use. ↓
https://discord.com/application-directory/861967109985927208

**Comment by Luongzz** [comment]
thank u
